apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 146230907561.dkr.ecr.ap-northeast-1.amazonaws.com/guestbook
  newTag: b0779b9c9c6bd6f15a6401f3f60ced14508ee9b0
- name: frontend
  newName: guestbook
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1d
- name: guestbook
  newName: guestbook
  newTag: new
